[package]
name = "s16-compiler"
version = "0.1.0"
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
logos = "0.15.1"
lalrpop-util = "0.22.2"
thiserror = "2.0.17"
#ariadne = "0.5.1"

[build-dependencies]
lalrpop = "0.22.2"

